name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Ruby dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Node.js dependencies
        run: npm ci

      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        env:
          RUBYOPT: "-W:no-deprecated"

      - name: Setup database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rails assets:precompile
        env:
          RAILS_ENV: test
          RUBYOPT: "-W:no-deprecated"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Lint ERB
        run: ./bin/erblint --lint-all
        env:
          RAILS_ENV: test
          RUBYOPT: "-W:no-deprecated"

      - name: Lint JavaScript
        run: npm run lint-js
        env:
          RAILS_ENV: test
          RUBYOPT: "-W:no-deprecated"

      - name: Lint Ruby
        run: ./bin/rubocop
        env:
          RAILS_ENV: test
          RUBYOPT: "-W:no-deprecated"

      - name: RSpec
        run: COVERAGE=true bin/rspec
        env:
          RAILS_ENV: test
          RUBYOPT: "-W:no-deprecated"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
